"""Added branch_id field to customers table

Revision ID: 13aa22a9ad2d
Revises: f0e33db5d57a
Create Date: 2025-02-16 15:38:28.091077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13aa22a9ad2d'
down_revision: Union[str, None] = 'f0e33db5d57a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('branch_id', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'customers', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'branch_id')
    # ### end Alembic commands ###
