"""Added column: purchase_invoice_id

Revision ID: ca4f540fce34
Revises: 4a699215d1cc
Create Date: 2025-01-28 12:17:44.807220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca4f540fce34'
down_revision: Union[str, None] = '4a699215d1cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_payments', sa.Column('purchase_invoice_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'supplier_payments', 'purchase_invoices', ['purchase_invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier_payments', type_='foreignkey')
    op.drop_column('supplier_payments', 'purchase_invoice_id')
    # ### end Alembic commands ###
