"""Added default value for branch transfer requests

Revision ID: e31f18e22419
Revises: 13aa22a9ad2d
Create Date: 2025-02-16 17:18:21.132882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e31f18e22419'
down_revision: Union[str, None] = '13aa22a9ad2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
