"""Removed log_date field from the Inventory log model

Revision ID: f0e33db5d57a
Revises: 8a70d203b288
Create Date: 2025-02-09 22:28:04.401472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e33db5d57a'
down_revision: Union[str, None] = '8a70d203b288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_logs', 'log_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_logs', sa.Column('log_date', sa.DATE(), nullable=False))
    # ### end Alembic commands ###
